# Generated by Django 4.0.4 on 2022-05-27 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finances.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_charge', models.CharField(max_length=10, verbose_name='Cost of Service Per Month')),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inv_no', models.CharField(default=finances.models.increment_invoice_number, max_length=50, unique=True, verbose_name='Invoice Number')),
                ('invoice_amount', models.CharField(max_length=10, verbose_name='Amount Invoiced')),
                ('invoice_balance', models.CharField(max_length=10, verbose_name='Invoice Balance')),
                ('extra_charges', models.CharField(blank=True, max_length=10, verbose_name='Extra charges')),
                ('invoice_date', models.DateField(auto_now_add=True, verbose_name='Invoice Date')),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.client_service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=30, verbose_name='Service Name')),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recpt_no', models.CharField(default=finances.models.increment_receipt_number, max_length=50, unique=True, verbose_name='Invoice Number')),
                ('amount_paid', models.CharField(max_length=10, verbose_name='Receipt Amount')),
                ('receipt_date', models.DateField(auto_now_add=True, verbose_name='Receipt Date')),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment_Method',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=20, verbose_name='Method Name')),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client_service',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.service'),
        ),
        migrations.AddField(
            model_name='client_service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
