# Generated by Django 4.0.4 on 2022-06-27 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_category_monthly_charge'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client_service',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(default='de60ed8f-8034-4829-8c1d-24c8f57b1c5a', on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='balance',
            field=models.CharField(blank=True, max_length=20, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount_paid',
            field=models.CharField(max_length=20, verbose_name='Receipt Amount'),
        ),
    ]
